version: '3.1'

services:
  
  web:
    build:
      context: ${APP_DIR}
      dockerfile: ${DEV_PATH}/Dockerfile
      args:
        DEV_PATH: ${DEV_PATH}
    command: bin/server
    volumes:
      - ${APP_DIR}:/app
    ports:
      - "8080:8080"
    env_file:
      - '.env'
